name: proximity_voice_chat
description: Aplicacion movil para el chat de voz de proximidad en Minecraft Bedrock.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0
  permission_handler: ^11.0.0
  flutter_sound: ^9.2.13
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  flutter_background: ^2.4.0
  flutter_local_notifications: ^16.0.0
  wakelock_plus: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
